version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    stdin_open: true
    tty: true
    command:  >
      bash -c "python --version
      && python src/manage.py makemigrations
      && python src/manage.py makemigrations api
      && python src/manage.py migrate
      && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db